import org.apache.tools.ant.taskdefs.condition.Os

plugins {
    id 'java'
}

group 'com.waterloorocketry'
version '0.5'

repositories {
    flatDir {
        dirs './'
    }
    mavenCentral()
}

dependencies {
    implementation name: 'OpenRocket-23.09', version: '23.09', group: 'net.sf.openrocket'


    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
}

test {
    useJUnitPlatform()
}

// Ensure the JAR includes the native library at the root
// This allows LibraryLoader.java to find it via getResource("/lib...")
sourceSets {
    main {
        resources {
            // Include the compiled native libraries
            srcDirs 'build/natives/lib'
            srcDirs 'build/natives/bin'
        }
    }
}





// OPTIONAL: Run task for testing inside Gradle
tasks.register('run', JavaExec) {
    dependsOn jar
    mainClass = 'net.sf.openrocket.startup.OpenRocket'
    classpath = files('./OpenRocket-23.09.jar', tasks.jar)
}

tasks.register('tune', JavaExec) {
    dependsOn jar
    mainClass = 'com.waterloorocketry.airbrakeplugin.PidTuner'
    classpath = files('./OpenRocket-23.09.jar', tasks.jar)
}